[package]
name = "mmphf-rust"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[[bin]]
name = "Comparison"
path = "src/main.rs"

[dependencies]
sux = { git = "https://github.com/vigna/sux-rs", features = ["rayon"] }
anyhow = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
env_logger = "0.11"
log = "0.4"
mem_dbg = "0.4"
rand = "0.10"
dsi-progress-logger = "0.8"

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = "fat"
